#!/bin/sh
#
# inseminate: an Entropy-as-a-Service client
#
#  inseminate is a fork of pollinate by Dustin Kirkland found at:
#       https://github.com/dustinkirkland/pollinate/blob/master/pollinate
#
# Put in crontab as follows:
#       * * * * * sh inseminate > /dev/random
#
#  Copyright (C) 2015 Aaron Toponce <aaron.toponce@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, version 3 of the License.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Working directory
TMPDIR=$(mktemp -d -t "inseminate.XXXXXXXXXXXX")

# Construct a user agent, with useful debug information
CURL_VER="$(apt-cache policy curl | awk '/Installed:/ {print $2}')"
LSB="$(lsb_release -is)/$(lsb_release -rs)"
PLATFORM="$(uname -o)/$(uname -r)/$(uname -m)"
USER_AGENT="inseminate/0.2 curl/$CURL_VER $LSB $PLATFORM"

# Setup the challenge with a response
CHALLENGE=$(head -c 64 /dev/urandom | sha512sum | awk '{print $1}')
CHALLENGE_RESPONSE=$(echo -n "$CHALLENGE" | sha512sum | awk '{print $1}')
F1=$(echo -n "challenge=$CHALLENGE")

# Get the data
curl -A "$USER_AGENT" -o- -v --trace-time --connect-timeout 3 -m 3 -d $F1 \
    https://entropy.ubuntu.com > "${TMPDIR}/out" 2> "${TMPDIR}/err"

RESPONSE=$(head -n 1 "${TMPDIR}/out")
RESULT=$(cat "${TMPDIR}/out" "${TMPDIR}/err" | sha512sum | awk '{print $1}')
[ "$CHALLENGE_RESPONSE" = "$RESPONSE" ] && echo "$RESULT"

rm -rf "$TMPDIR"
